# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/lgc_location_api/v1/lgc_location_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.lgc_location_api.v1.lgc_location_api_pb2


class OmpTemplateApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeTemplateV1(self, stream: 'grpclib.server.Stream[ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Request, ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.lgc_location_api.v1.OmpTemplateApiService/DescribeTemplateV1': grpclib.const.Handler(
                self.DescribeTemplateV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Request,
                ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Response,
            ),
        }


class OmpTemplateApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeTemplateV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.lgc_location_api.v1.OmpTemplateApiService/DescribeTemplateV1',
            ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Request,
            ozonmp.lgc_location_api.v1.lgc_location_api_pb2.DescribeTemplateV1Response,
        )
